### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by grosch** [skelpo/JWTMiddleware#11]
Could you post some concrete examples of how to use this please?

**Comment by proggeramlug** [comment]
Yes, we are actually working on two other projects that will use this middleware and will be published as Open Source in the close future. By the end of the week we should have an example up and running!

**Comment by proggeramlug** [comment]
Check this out: https://github.com/skelpo/JWTAuthExample 

I think that should give you a good idea how to use it! :) Any questions?

**Comment by grosch** [comment]
Kinda sorta.  I'm brand new to security so yah, I could copy the code, but I'm not entirely sure "what" it's doing.   I know, not really your problem, but I think lots of people would be in the same boat as me here.

**Comment by proggeramlug** [comment]
Well, I'm all in on helping people use good solutions for their problems.

In that repo you also find _what_ exactly is happening in the readme. Once you grasp the concept of JWT it should not be too difficult.
